/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import connection.conexao;
import model.PlanoEnum;
import dao.alunosDao;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AlunosModel;
import model.Utilitarios;
//import dao.alunosDao;
//import model.Alunos;

/**
 *
 * @author mmgti
 */
public class Alunos extends javax.swing.JFrame {

    /**
     * Creates new form Alunos
     */
    //Connection con = null ;
    //PreparedStatement pst = null ;
    //ResultSet rs = null;
    public void listar() {

        alunosDao dao = new alunosDao();
        List<AlunosModel> lista = dao.listarAlunos();
        DefaultTableModel dados = (DefaultTableModel) tabelaAluno.getModel();
        dados.setNumRows(0);
        for (AlunosModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
                c.getPlano(),
                c.getMensalidade(),
                c.getIdade()});
        }
    }

    public Alunos() {
        initComponents();
        // con = conexao.conector();
        //System.out.println(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCadastroAluno = new javax.swing.JPanel();
        LabelEmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        LabelNome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        LabelCelular = new javax.swing.JLabel();
        txtcep = new javax.swing.JFormattedTextField();
        LabelTelefone = new javax.swing.JLabel();
        txttelefone = new javax.swing.JFormattedTextField();
        LabeCepl = new javax.swing.JLabel();
        txtcelular = new javax.swing.JFormattedTextField();
        LabelEndereco = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        LabelNumero = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        LabelBairro = new javax.swing.JLabel();
        txtcomplemento = new javax.swing.JTextField();
        LabelCidade = new javax.swing.JLabel();
        LabelComplemento = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        LabelUf = new javax.swing.JLabel();
        cbuf = new javax.swing.JComboBox<>();
        LabelRg = new javax.swing.JLabel();
        txtcpf = new javax.swing.JFormattedTextField();
        LabelCpf = new javax.swing.JLabel();
        txtrg = new javax.swing.JFormattedTextField();
        txtbairro = new javax.swing.JTextField();
        LabelPlano = new javax.swing.JLabel();
        cbplano = new javax.swing.JComboBox<>();
        txtcodigo = new javax.swing.JTextField();
        LabelCodigo = new javax.swing.JLabel();
        ButtonBuscar = new javax.swing.JButton();
        LabelMensalidade = new javax.swing.JLabel();
        txtidade = new javax.swing.JTextField();
        LabelIdade = new javax.swing.JLabel();
        txtmensalidade = new javax.swing.JTextField();
        PanelConsultaAluno = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ButtonPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();
        ButtonSalvar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro Alunos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(769, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Sistema Academia");

        PanelCadastroAluno.setBackground(new java.awt.Color(255, 255, 255));

        LabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelEmail.setText("E-mail");

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNome.setText("Nome");

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCelular.setText("Celular");

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcepActionPerformed(evt);
            }
        });
        txtcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcepKeyPressed(evt);
            }
        });

        LabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTelefone.setText("Telefone");

        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabeCepl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabeCepl.setText("CEP");

        try {
            txtcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelEndereco.setText("Endereço");

        txtnumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNumero.setText("N:");

        txtendereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelBairro.setText("Bairro");

        txtcomplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCidade.setText("Cidade");

        LabelComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelComplemento.setText("Complemento");

        txtcidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelUf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelUf.setText("UF");

        cbuf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RN", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "AC", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        LabelRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelRg.setText("RG");

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcpfKeyPressed(evt);
            }
        });

        LabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCpf.setText("CPF");

        try {
            txtrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtrg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtbairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelPlano.setText("Plano");

        cbplano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbplano.setForeground(new java.awt.Color(0, 0, 204));
        cbplano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  PLANO_INICIAL", "  PLANO_BASE", "  PLANO_TOTAL" }));
        cbplano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbplanoItemStateChanged(evt);
            }
        });

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCodigo.setText("Mat:");

        ButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonBuscar.setText("Busca");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        LabelMensalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelMensalidade.setText("Mensalidade");

        txtidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidadeActionPerformed(evt);
            }
        });

        LabelIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelIdade.setText("Idade");

        txtmensalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout PanelCadastroAlunoLayout = new javax.swing.GroupLayout(PanelCadastroAluno);
        PanelCadastroAluno.setLayout(PanelCadastroAlunoLayout);
        PanelCadastroAlunoLayout.setHorizontalGroup(
            PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelEndereco)
                    .addComponent(LabeCepl)
                    .addComponent(LabelRg)
                    .addComponent(LabelNome)
                    .addComponent(LabelPlano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonBuscar)
                            .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(LabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284))
                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(LabelCodigo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadastroAlunoLayout.createSequentialGroup()
                                        .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelCpf))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadastroAlunoLayout.createSequentialGroup()
                                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadastroAlunoLayout.createSequentialGroup()
                                                .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LabelCidade))
                                            .addComponent(cbplano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtidade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                            .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(LabelUf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2)
                                            .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                                .addComponent(cbuf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcpf, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(txtcodigo))
                                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LabelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroAlunoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LabelMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LabelBairro)
                                            .addComponent(LabelEmail))
                                        .addGap(29, 29, 29)
                                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbairro)))
                                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtmensalidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                            .addComponent(LabelComplemento, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(LabelCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                        .addGap(107, 107, 107))))
        );
        PanelCadastroAlunoLayout.setVerticalGroup(
            PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCelular)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTelefone)
                    .addComponent(ButtonBuscar))
                .addGap(11, 11, 11)
                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelRg)
                                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelCpf)
                                .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelComplemento)
                                .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(PanelCadastroAlunoLayout.createSequentialGroup()
                        .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroAlunoLayout.createSequentialGroup()
                                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelEndereco)
                                        .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelNumero)))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabeCepl)
                                .addComponent(LabelCidade)
                                .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelUf)
                                .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)))
                .addGroup(PanelCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbplano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPlano)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCodigo)
                    .addComponent(LabelMensalidade)
                    .addComponent(txtmensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro Alunos", PanelCadastroAluno);

        PanelConsultaAluno.setBackground(new java.awt.Color(255, 255, 255));

        txtpesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nome");

        ButtonPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonPesquisa.setText("Pesquisar");
        ButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisaActionPerformed(evt);
            }
        });

        tabelaAluno.setBackground(new java.awt.Color(204, 255, 255));
        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "RG", "CPF", "E-mail", "Telefone", "Celular", "Cep", "Endereço", "Numero", "Complemento", "Bairro", "Cidade", "UF", "Plano ", "Mensalidade", "idade"
            }
        ));
        tabelaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAluno);

        javax.swing.GroupLayout PanelConsultaAlunoLayout = new javax.swing.GroupLayout(PanelConsultaAluno);
        PanelConsultaAluno.setLayout(PanelConsultaAlunoLayout);
        PanelConsultaAlunoLayout.setHorizontalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        PanelConsultaAlunoLayout.setVerticalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ButtonPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Alunos", PanelConsultaAluno);

        ButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });
        ButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonSalvarKeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        ButtonEditar.setText("Editar");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonSalvar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        ButtonSalvar1.setText("Novo");
        ButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(ButtonSalvar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvar)
                    .addComponent(ButtonEditar)
                    .addComponent(jButton4)
                    .addComponent(ButtonSalvar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("CadastroFuncionarios");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        // botao salvar
        
        // 1 passo pega os dados que foram digitado tela view  e armazenar dentro do objeto  AlunosModel 
        // criar o bjeto 
        AlunosModel obj = new AlunosModel();
        
        //2  pega os dados guardar dentro do obj 

        obj.setNome(txtnome.getText());// pega da caixinha txtnome e armazenar dentro do atributo setnome dentro do objeto  
        obj.setRg(txtrg.getText());
        obj.setCpf(txtcpf.getText());
        obj.setEmail(txtemail.getText());
        obj.setTelefone(txttelefone.getText());
        obj.setCelular(txtcelular.getText());
        obj.setCep(txtcep.getText());
        obj.setEndereco(txtendereco.getText());
        obj.setNumero(Integer.parseInt(txtnumero.getText()));
        obj.setComplemento(txtcomplemento.getText());
        obj.setBairro(txtbairro.getText());
        obj.setCidade(txtcidade.getText());
        obj.setUf(cbuf.getSelectedItem().toString());
        obj.setPlano(cbplano.getSelectedItem().toString());
        obj.setMensalidade(Integer.parseInt(txtmensalidade.getText()));
        obj.setIdade(Integer.parseInt(txtidade.getText()));
        obj.setId(Integer.parseInt(txtcodigo.getText()));
        
       // 3 passo criar objeto camada dao para cadastrar esse obj model no banco de dados 
        alunosDao dao = new alunosDao();
        
        new Utilitarios().LimpaTela(PanelCadastroAluno);
        if (obj.getIdade() > 10) {

            dao.cadastrarAluno(obj);// metodo cadastrarAluno passando obj 
        } else {

            JOptionPane.showMessageDialog(null, "Aluno não pode ser cadastrado idade inferior 10 anos ");
        }


    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        // botao editar 

        AlunosModel obj = new AlunosModel();

        obj.setNome(txtnome.getText());
        obj.setRg(txtrg.getText());
        obj.setCpf(txtcpf.getText());
        obj.setEmail(txtemail.getText());
        obj.setTelefone(txttelefone.getText());
        obj.setCelular(txtcelular.getText());
        obj.setCep(txtcep.getText());
        obj.setEndereco(txtendereco.getText());
        obj.setNumero(Integer.parseInt(txtnumero.getText()));
        obj.setComplemento(txtcomplemento.getText());
        obj.setBairro(txtbairro.getText());
        obj.setCidade(txtcidade.getText());
        obj.setUf(cbuf.getSelectedItem().toString());
        obj.setPlano(cbplano.getSelectedItem().toString());
        obj.setMensalidade(Integer.parseInt(txtmensalidade.getText()));
        obj.setIdade(Integer.parseInt(txtidade.getText()));
        obj.setId(Integer.parseInt(txtcodigo.getText()));

        alunosDao dao = new alunosDao();
        dao.alterarAluno(obj);

        new Utilitarios().LimpaTela(PanelCadastroAluno);


    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // carrega a lista
        listar();

    }//GEN-LAST:event_formWindowActivated

    private void tabelaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunoMouseClicked
        // pega dados da tabela no click do mouse
        jTabbedPane1.setSelectedIndex(0);// muda de aba volta ao clicar no registro
        txtcodigo.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 0).toString());
        txtnome.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 1).toString());
        txtrg.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 2).toString());
        txtcpf.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 3).toString());
        txtemail.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 4).toString());
        txttelefone.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 5).toString());
        txtcelular.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 6).toString());
        txtcep.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 7).toString());
        txtendereco.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 8).toString());
        txtnumero.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 9).toString());
        txtcomplemento.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 10).toString());
        txtbairro.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 11).toString());
        txtcidade.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 12).toString());
        cbuf.setSelectedItem(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 13).toString());
        cbplano.setSelectedItem(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 14).toString());
        txtmensalidade.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 15).toString());
        txtidade.setText(tabelaAluno.getValueAt(tabelaAluno.getSelectedRow(), 16).toString());


    }//GEN-LAST:event_tabelaAlunoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Botao Excluir

        AlunosModel obj = new AlunosModel();

        obj.setId(Integer.parseInt(txtcodigo.getText()));
        alunosDao dao = new alunosDao();
        dao.excluirAluno(obj);
        new Utilitarios().LimpaTela(PanelCadastroAluno);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void ButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisaActionPerformed
        // pesquisa por nome
        String nome = "%" + txtpesquisa.getText() + "%";//sintaxe do sql % caracter qualquer coisa antes e depois
        alunosDao dao = new alunosDao();
        List<AlunosModel> lista = dao.buscaAlunoPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaAluno.getModel();
        dados.setNumRows(0);
        for (AlunosModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
                c.getPlano(),
                c.getMensalidade(),
                c.getIdade()});
        }


    }//GEN-LAST:event_ButtonPesquisaActionPerformed

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
        // escreve no campo de pesquisa 
        String nome = "%" + txtpesquisa.getText() + "%";//sintaxe do sql % caracter qualquer coisa antes e depois
        alunosDao dao = new alunosDao();
        List<AlunosModel> lista = dao.buscaAlunoPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaAluno.getModel();
        dados.setNumRows(0);
        for (AlunosModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
                c.getPlano(),
                c.getMensalidade(),
                c.getIdade()
            });
        }

    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // botao buscar por nome 
        String nome = txtnome.getText();
        AlunosModel obj = new AlunosModel();
        alunosDao dao = new alunosDao();

        obj = dao.consultarPorNome(nome);

        if (obj.getNome() != null) {

            txtcodigo.setText(String.valueOf(obj.getId()));
            txtnome.setText(obj.getNome());
            txtrg.setText(obj.getRg());
            txtcpf.setText(obj.getCpf());
            txtemail.setText(obj.getEmail());
            txttelefone.setText(obj.getTelefone());
            txtcelular.setText(obj.getCelular());
            txtcep.setText(obj.getCep());
            txtendereco.setText(obj.getEndereco());
            txtnumero.setText(String.valueOf(obj.getNumero()));
            txtcomplemento.setText(obj.getComplemento());
            txtbairro.setText(obj.getBairro());
            txtcidade.setText(obj.getCidade());
            cbuf.setSelectedItem(obj.getUf());
            cbplano.setSelectedItem(obj.getPlano());
            txtmensalidade.setText(String.valueOf(obj.getMensalidade()));
            txtidade.setText(String.valueOf(obj.getIdade()));
        } else {
            JOptionPane.showMessageDialog(null, "Aluno não encontrado");
        }

    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvar1ActionPerformed
        // Botao novo

        new Utilitarios().LimpaTela(PanelCadastroAluno);

    }//GEN-LAST:event_ButtonSalvar1ActionPerformed

    private void txtcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcepKeyPressed
        //Programacao do keypress
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            AlunosModel obj = new AlunosModel();
            alunosDao dao = new alunosDao();
            obj = dao.AlunosCep(txtcep.getText());

            txtendereco.setText(obj.getEndereco());
            txtbairro.setText(obj.getBairro());
            txtcidade.setText(obj.getCidade());
            cbuf.setSelectedItem(obj.getUf());
            System.out.println(obj.getUf());

        }

    }//GEN-LAST:event_txtcepKeyPressed

    private void ButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonSalvarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSalvarKeyPressed

    private void txtcpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfKeyPressed

    private void txtcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcepActionPerformed

    private void txtidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidadeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtidadeActionPerformed

    private void cbplanoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbplanoItemStateChanged
        //
        System.out.println(String.format("%.2f", 10f));
      //  PlanoEnum plano = PlanoEnum.valueOf(evt.getItem().toString());
        if (evt.getItem().equals( PlanoEnum.PLANO_INICIAL.name())) {
            
            txtmensalidade.setText(String.valueOf(PlanoEnum.PLANO_INICIAL.valor));
            
        } else {
            
        }
    }//GEN-LAST:event_cbplanoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonPesquisa;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonSalvar1;
    private javax.swing.JLabel LabeCepl;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCelular;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelComplemento;
    private javax.swing.JLabel LabelCpf;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelIdade;
    private javax.swing.JLabel LabelMensalidade;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelPlano;
    private javax.swing.JLabel LabelRg;
    private javax.swing.JLabel LabelTelefone;
    private javax.swing.JLabel LabelUf;
    private javax.swing.JPanel PanelCadastroAluno;
    private javax.swing.JPanel PanelConsultaAluno;
    private javax.swing.JComboBox<String> cbplano;
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JFormattedTextField txtcelular;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtidade;
    private javax.swing.JTextField txtmensalidade;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JFormattedTextField txtrg;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
