/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FuncionarioDao;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FuncionarioModel;
import model.Utilitarios;

/**
 *
 * @author mmgti
 */
public class Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCadastroFuncionarios = new javax.swing.JPanel();
        LabelEmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        LabelNome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        LabelCelular = new javax.swing.JLabel();
        txtcepfuncionario = new javax.swing.JFormattedTextField();
        LabelTelefone = new javax.swing.JLabel();
        txttelefone = new javax.swing.JFormattedTextField();
        LabeCepl = new javax.swing.JLabel();
        txtcelular = new javax.swing.JFormattedTextField();
        LabelEndereco = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        LabelNumero = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        LabelBairro = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        LabelCidade = new javax.swing.JLabel();
        LabelComplemento = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        LabelUf = new javax.swing.JLabel();
        cbuf = new javax.swing.JComboBox<>();
        LabelRg = new javax.swing.JLabel();
        txtcpf = new javax.swing.JFormattedTextField();
        LabelCpf = new javax.swing.JLabel();
        txtrg = new javax.swing.JFormattedTextField();
        txtbairro = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        LabelCodigo = new javax.swing.JLabel();
        ButtonBuscar = new javax.swing.JButton();
        txtsalario = new javax.swing.JTextField();
        cbNivel_Acesso = new javax.swing.JComboBox<>();
        LabelNivelAcesso = new javax.swing.JLabel();
        LabelCargo = new javax.swing.JLabel();
        LabelSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        LabelSalario = new javax.swing.JLabel();
        txtcomplementofun1 = new javax.swing.JTextField();
        PanelConsultaAluno = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ButtonPesquisaFuncionario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        ButtonSalvar = new javax.swing.JButton();
        ButtonExcluir = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Funcionários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(679, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PanelCadastroFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        PanelCadastroFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCadastroFuncionariosMouseClicked(evt);
            }
        });

        LabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelEmail.setText("E-mail");

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        LabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNome.setText("Nome");

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCelular.setText("Celular");

        try {
            txtcepfuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcepfuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcepfuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcepfuncionarioKeyPressed(evt);
            }
        });

        LabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTelefone.setText("Telefone");

        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabeCepl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabeCepl.setText("CEP");

        try {
            txtcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelEndereco.setText("Endereço");

        txtnumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNumero.setText("N:");

        txtendereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelBairro.setText("Bairro");

        txtcargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCidade.setText("Cidade");

        LabelComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelComplemento.setText("Complemento");

        txtcidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelUf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelUf.setText("UF");

        cbuf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RN", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "AC", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        LabelRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelRg.setText("RG");

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCpf.setText("CPF");

        try {
            txtrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtrg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtbairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCodigo.setText("Mat:");

        ButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonBuscar.setText("Busca");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        txtsalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalarioActionPerformed(evt);
            }
        });

        cbNivel_Acesso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNivel_Acesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador", " " }));

        LabelNivelAcesso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNivelAcesso.setText("Nivel Acesso");

        LabelCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCargo.setText("Cargo");

        LabelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelSenha.setText("Senha:");

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelSalario.setText("Salario");

        txtcomplementofun1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout PanelCadastroFuncionariosLayout = new javax.swing.GroupLayout(PanelCadastroFuncionarios);
        PanelCadastroFuncionarios.setLayout(PanelCadastroFuncionariosLayout);
        PanelCadastroFuncionariosLayout.setHorizontalGroup(
            PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelEndereco)
                    .addComponent(LabeCepl)
                    .addComponent(LabelRg)
                    .addComponent(LabelNome)
                    .addComponent(LabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(ButtonBuscar))
                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addComponent(LabelUf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(LabelCelular)
                                                .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                                    .addComponent(LabelNumero)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LabelTelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addComponent(LabelBairro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtbairro))
                                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addComponent(LabelEmail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtemail))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroFuncionariosLayout.createSequentialGroup()
                                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addComponent(LabelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                                .addComponent(LabelNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbNivel_Acesso, 0, 1, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LabelSalario)
                                            .addComponent(LabelComplemento))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcomplementofun1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                            .addComponent(txtsalario))))))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(txtcepfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelCidade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadastroFuncionariosLayout.createSequentialGroup()
                                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(LabelCpf))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroFuncionariosLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(LabelCodigo)))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(txtcidade)
                                .addGap(557, 557, 557))
                            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcpf, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(txtcodigo))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        PanelCadastroFuncionariosLayout.setVerticalGroup(
            PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCelular)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTelefone)
                    .addComponent(ButtonBuscar))
                .addGap(11, 11, 11)
                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEndereco)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBairro)
                    .addComponent(LabelNumero)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroFuncionariosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcepfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabeCepl)
                            .addComponent(LabelCidade)
                            .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelUf)
                            .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroFuncionariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEmail)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRg)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCargo)
                    .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCpf)
                    .addComponent(LabelComplemento)
                    .addComponent(txtcomplementofun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSalario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelCodigo)
                        .addComponent(LabelNivelAcesso)
                        .addComponent(cbNivel_Acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelSenha)
                        .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro Funcionário", PanelCadastroFuncionarios);

        PanelConsultaAluno.setBackground(new java.awt.Color(255, 255, 255));

        txtpesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nome");

        ButtonPesquisaFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonPesquisaFuncionario.setText("Pesquisar");
        ButtonPesquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisaFuncionarioActionPerformed(evt);
            }
        });

        tabelaFuncionario.setBackground(new java.awt.Color(204, 255, 255));
        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "RG", "CPF", "E-mail", "Senha", "cargo", "Nivel_Acesso", "Telefone", "Celular", "Cep", "Endereço", "Numero", "Complemento", "Bairro", "Cidade", "UF", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionarioMouseClicked(evt);
            }
        });
        tabelaFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaFuncionarioKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionario);

        javax.swing.GroupLayout PanelConsultaAlunoLayout = new javax.swing.GroupLayout(PanelConsultaAluno);
        PanelConsultaAluno.setLayout(PanelConsultaAlunoLayout);
        PanelConsultaAlunoLayout.setHorizontalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPesquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(620, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        PanelConsultaAlunoLayout.setVerticalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ButtonPesquisaFuncionario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Funcionário", PanelConsultaAluno);

        ButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });
        ButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonSalvarKeyPressed(evt);
            }
        });

        ButtonExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        ButtonExcluir.setText("Excluir");
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });

        ButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        ButtonEditar.setText("Editar");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonSalvar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        ButtonSalvar1.setText("Novo");
        ButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSalvar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonExcluir)
                .addGap(346, 346, 346))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvar)
                    .addComponent(ButtonEditar)
                    .addComponent(ButtonExcluir)
                    .addComponent(ButtonSalvar1))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  // metodo carregar tabela 
    public void listar() {

        FuncionarioDao dao = new FuncionarioDao();
        List<FuncionarioModel> lista = dao.listarFuncionario();
        // criando os objecto dados para armazernar na tabelafuncionari
        DefaultTableModel dados = (DefaultTableModel) tabelaFuncionario.getModel(); 
        
        dados.setNumRows(0);// limpa os dados 
        
        // para cada item desta lista ele vai criar um objecto chamaodo c e esse c adiciono na lista 
        for (FuncionarioModel c : lista) {
            dados.addRow(new Object[]{// pra cada linha eu vo adiconar um novo vetor de objeto 
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getSenha(),
                c.getCargo(),
                c.getNivel_Acesso(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
                c.getSalario(),});
        }
        
    }
    private void txtcepfuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcepfuncionarioKeyPressed
        //Programacao do keypress
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            FuncionarioModel obj = new FuncionarioModel();
            FuncionarioDao dao = new FuncionarioDao();
            obj = (FuncionarioModel) dao.FuncionarioCep(txtcepfuncionario.getText());

            txtendereco.setText(obj.getEndereco());
            txtbairro.setText(obj.getBairro());
            txtcidade.setText(obj.getCidade());
            cbuf.setSelectedItem(obj.getUf());
            System.out.println(obj.getUf());

        }
    }//GEN-LAST:event_txtcepfuncionarioKeyPressed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // botao buscar por nome
        String nome = txtnome.getText();
        FuncionarioModel obj = new FuncionarioModel();
        FuncionarioDao dao = new FuncionarioDao();

        obj = dao.consultarPorNome(nome);

        if (obj.getNome() != null) {

            txtcodigo.setText(String.valueOf(obj.getId()));
            txtnome.setText(obj.getNome());
            txtrg.setText(obj.getRg());
            txtcpf.setText(obj.getCpf());
            txtemail.setText(obj.getEmail());
            txtSenha.setText(obj.getSenha());
            txtcargo.setText(obj.getSenha());
            cbNivel_Acesso.setSelectedItem(obj.getNivel_Acesso());
            txttelefone.setText(obj.getTelefone());
            txtcelular.setText(obj.getCelular());
            txtcepfuncionario.setText(obj.getCep());
            txtendereco.setText(obj.getEndereco());
            txtnumero.setText(String.valueOf(obj.getNumero()));
            txtsalario.setText(obj.getComplemento());
            txtcargo.setText(obj.getComplemento());
            txtbairro.setText(obj.getBairro());
            txtcidade.setText(obj.getCidade());
            cbuf.setSelectedItem(obj.getUf());
           txtsalario.setText(String.format("%.2f",obj.getSalario()));

        } else {
            JOptionPane.showMessageDialog(null, "Aluno não encontrado");
        }

    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
        // escreve no campo de pesquisa
        String nome = "%" + txtpesquisa.getText() + "%";//sintaxe do sql % caracter qualquer coisa antes e depois
        FuncionarioDao dao = new FuncionarioDao();
        List<FuncionarioModel> lista = dao.buscaFuncionarioPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaFuncionario.getModel();
        dados.setNumRows(0);
        for (FuncionarioModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getSenha(),
                c.getCargo(),
                c.getNivel_Acesso(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
                c.getSalario()});
        }
    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void ButtonPesquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisaFuncionarioActionPerformed
        // pesquisa por nome
        String nome = "%" + txtpesquisa.getText() + "%";//sintaxe do sql % caracter qualquer coisa antes e depois
        FuncionarioDao dao = new FuncionarioDao();
        List<FuncionarioModel> lista = dao.buscaFuncionarioPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel)tabelaFuncionario.getModel();
        dados.setNumRows(0);
        for (FuncionarioModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getSenha(),
                c.getCargo(),
                c.getNivel_Acesso(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf(),
                c.getSalario()});
        }

    }//GEN-LAST:event_ButtonPesquisaFuncionarioActionPerformed

    private void tabelaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionarioMouseClicked
        // pega dados da tabela no click do mouse
       // muda de aba volta ao clicar no registro
        txtcodigo.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 0).toString());
        txtnome.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 1).toString());
        txtrg.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 2).toString());
        txtcpf.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 3).toString());
        txtemail.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 4).toString());
        txtSenha.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 5).toString());
        txtcargo.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 6).toString());
        cbNivel_Acesso.setSelectedItem(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 7).toString());
        txttelefone.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 8).toString());
        txtcelular.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 9).toString());
        txtcepfuncionario.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 10).toString());
        txtendereco.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 11).toString());
        txtnumero.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 12).toString()); 
        txtcomplementofun1.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 13).toString()); 
        txtbairro.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 14).toString());
        txtcidade.setText(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 15).toString());
        cbuf.setSelectedItem(tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 16).toString());
        txtsalario.setText(String.format("%.2f",tabelaFuncionario.getValueAt(tabelaFuncionario.getSelectedRow(), 17)));
        
          //System.out.println(String.format("%.2f", 10f));

    }//GEN-LAST:event_tabelaFuncionarioMouseClicked

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        // botao salvar

        FuncionarioModel obj = new FuncionarioModel();

        obj.setNome(txtnome.getText());
        obj.setRg(txtrg.getText());
        obj.setCpf(txtcpf.getText());
        obj.setEmail(txtemail.getText());
        obj.setSenha(txtSenha.getText());
        obj.setCargo(txtcargo.getText());
        obj.setNivel_Acesso(cbNivel_Acesso.getSelectedItem().toString());
        obj.setTelefone(txttelefone.getText());
        obj.setCelular(txtcelular.getText());
        obj.setCep(txtcepfuncionario.getText());
        obj.setEndereco(txtendereco.getText());
        obj.setNumero(Integer.parseInt(txtnumero.getText()));
        obj.setComplemento(txtcomplementofun1.getText());
        obj.setBairro(txtbairro.getText());
        obj.setCidade(txtcidade.getText());
        obj.setUf(cbuf.getSelectedItem().toString());
        obj.setSalario(Double.parseDouble(txtsalario.getText()));

        obj.setId(Integer.parseInt(txtcodigo.getText()));
        
        FuncionarioDao dao = new FuncionarioDao();
   
        new Utilitarios().LimpaTela(PanelCadastroFuncionarios);
        
        if(obj.getSalario()>0){
        
             dao.cadastrarFuncionario(obj);
        
        }else{
        
             JOptionPane.showMessageDialog(null, "não aceita numeros negativo");
        
        }
      

    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonSalvarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSalvarKeyPressed

    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        // Botao Excluir

        FuncionarioModel obj = new FuncionarioModel();

        obj.setId(Integer.parseInt(txtcodigo.getText()));
        FuncionarioDao dao = new FuncionarioDao();
        dao.excluirFuncionario(obj);
        new Utilitarios().LimpaTela(PanelCadastroFuncionarios);
    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        // botao editar
        FuncionarioModel obj = new FuncionarioModel();

        obj.setNome(txtnome.getText());
        obj.setRg(txtrg.getText());
        obj.setCpf(txtcpf.getText());
        obj.setEmail(txtemail.getText());
        obj.setSenha(txtSenha.getText());
        obj.setCargo(txtcargo.getText());
        obj.setNivel_Acesso(cbNivel_Acesso.getSelectedItem().toString());
        obj.setTelefone(txttelefone.getText());
        obj.setCelular(txtcelular.getText());
        obj.setCep(txtcepfuncionario.getText());
        obj.setEndereco(txtendereco.getText());
        obj.setNumero(Integer.parseInt(txtnumero.getText()));
        obj.setComplemento(txtcomplementofun1.getText());
        obj.setBairro(txtbairro.getText());
        obj.setCidade(txtcidade.getText());
        obj.setUf(cbuf.getSelectedItem().toString());
        obj.setSalario(Double.parseDouble(txtsalario.getText()));
        obj.setId(Integer.parseInt(txtcodigo.getText()));

        FuncionarioDao dao = new FuncionarioDao();
         dao.alterarFuncionario(obj);

        new Utilitarios().LimpaTela(PanelCadastroFuncionarios);
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void ButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvar1ActionPerformed
        // Botao novo

        new Utilitarios().LimpaTela(PanelCadastroFuncionarios);

    }//GEN-LAST:event_ButtonSalvar1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void tabelaFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaFuncionarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaFuncionarioKeyPressed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalarioActionPerformed
    
    }//GEN-LAST:event_txtsalarioActionPerformed

    private void PanelCadastroFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCadastroFuncionariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCadastroFuncionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonExcluir;
    private javax.swing.JButton ButtonPesquisaFuncionario;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonSalvar1;
    private javax.swing.JLabel LabeCepl;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCargo;
    private javax.swing.JLabel LabelCelular;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelComplemento;
    private javax.swing.JLabel LabelCpf;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelNivelAcesso;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelRg;
    private javax.swing.JLabel LabelSalario;
    private javax.swing.JLabel LabelSenha;
    private javax.swing.JLabel LabelTelefone;
    private javax.swing.JLabel LabelUf;
    private javax.swing.JPanel PanelCadastroFuncionarios;
    private javax.swing.JPanel PanelConsultaAluno;
    private javax.swing.JComboBox<String> cbNivel_Acesso;
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JFormattedTextField txtcelular;
    private javax.swing.JFormattedTextField txtcepfuncionario;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcomplementofun1;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JFormattedTextField txtrg;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
