/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import connection.conexao;
import dao.PlanoDao;
import dao.alunosDao;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AlunosModel;
import model.PlanoModel;
import model.Utilitarios;
//import dao.alunosDao;
//import model.Alunos;

/**
 *
 * @author mmgti
 */
public class Plano extends javax.swing.JFrame {

    /**
     * Creates new form Alunos
     */
    //Connection con = null ;
    //PreparedStatement pst = null ;
    //ResultSet rs = null;
    public void listar() {
        PlanoDao dao = new PlanoDao();
        List<PlanoModel> lista = dao.listarPlano();
        DefaultTableModel dados = (DefaultTableModel) tabelaPlano.getModel();
        dados.setNumRows(0);

        for (PlanoModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getDescricao(),
                c.getValor(),
                c.getAlunos().getNome()

            });

        }
    }

    public Plano() {
        initComponents();
        // con = conexao.conector();
        //System.out.println(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCadastrarPlano = new javax.swing.JPanel();
        LabelDescricao = new javax.swing.JLabel();
        txtdescricaoplano = new javax.swing.JTextField();
        LabelValor = new javax.swing.JLabel();
        txtValorPlano = new javax.swing.JTextField();
        LabelUf = new javax.swing.JLabel();
        cbalunoplano = new javax.swing.JComboBox();
        txtCodigoPlano = new javax.swing.JTextField();
        LabelCodigoPlano = new javax.swing.JLabel();
        ButtonBuscar = new javax.swing.JButton();
        PanelConsultaAluno = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ButtonPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPlano = new javax.swing.JTable();
        ButtonSalvar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Planos");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro do Plano");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Sistema Academia");

        PanelCadastrarPlano.setBackground(new java.awt.Color(255, 255, 255));
        PanelCadastrarPlano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCadastrarPlanoMouseClicked(evt);
            }
        });

        LabelDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelDescricao.setText("Descrição do tipo de plano");

        txtdescricaoplano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelValor.setText("Valor do plano");

        txtValorPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelUf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelUf.setText("Aluno");

        cbalunoplano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbalunoplano.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbalunoplanoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbalunoplano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbalunoplanoMouseClicked(evt);
            }
        });
        cbalunoplano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbalunoplanoActionPerformed(evt);
            }
        });

        txtCodigoPlano.setEditable(false);
        txtCodigoPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCodigoPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCodigoPlano.setText("Mat:");

        ButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonBuscar.setText("Busca");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastrarPlanoLayout = new javax.swing.GroupLayout(PanelCadastrarPlano);
        PanelCadastrarPlano.setLayout(PanelCadastrarPlanoLayout);
        PanelCadastrarPlanoLayout.setHorizontalGroup(
            PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastrarPlanoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelValor)
                    .addComponent(LabelDescricao)
                    .addComponent(LabelUf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastrarPlanoLayout.createSequentialGroup()
                        .addComponent(txtdescricaoplano, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelCadastrarPlanoLayout.createSequentialGroup()
                        .addGroup(PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelCadastrarPlanoLayout.createSequentialGroup()
                                .addComponent(txtValorPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelCodigoPlano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoPlano))
                            .addGroup(PanelCadastrarPlanoLayout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(ButtonBuscar))
                            .addComponent(cbalunoplano, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 403, Short.MAX_VALUE))))
        );
        PanelCadastrarPlanoLayout.setVerticalGroup(
            PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastrarPlanoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdescricaoplano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDescricao)
                    .addComponent(ButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelValor)
                    .addComponent(txtValorPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCodigoPlano)
                    .addComponent(txtCodigoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PanelCadastrarPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUf)
                    .addComponent(cbalunoplano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Plano", PanelCadastrarPlano);

        PanelConsultaAluno.setBackground(new java.awt.Color(255, 255, 255));

        txtpesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nome");

        ButtonPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonPesquisa.setText("Pesquisar");
        ButtonPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPesquisaMouseClicked(evt);
            }
        });
        ButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisaActionPerformed(evt);
            }
        });

        tabelaPlano.setBackground(new java.awt.Color(204, 255, 255));
        tabelaPlano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Plano", "Descrição Plano", "Valor ", "Aluno"
            }
        ));
        tabelaPlano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPlanoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPlano);

        javax.swing.GroupLayout PanelConsultaAlunoLayout = new javax.swing.GroupLayout(PanelConsultaAluno);
        PanelConsultaAluno.setLayout(PanelConsultaAlunoLayout);
        PanelConsultaAlunoLayout.setHorizontalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        PanelConsultaAlunoLayout.setVerticalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ButtonPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Plano", PanelConsultaAluno);

        ButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });
        ButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonSalvarKeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        ButtonEditar.setText("Editar");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonSalvar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        ButtonSalvar1.setText("Novo");
        ButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSalvar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(295, 295, 295))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvar)
                    .addComponent(ButtonEditar)
                    .addComponent(jButton4)
                    .addComponent(ButtonSalvar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("CadastroFuncionarios");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        // botao salvar

        PlanoModel obj = new PlanoModel();
        obj.setDescricao(txtdescricaoplano.getText());
        obj.setValor(Double.parseDouble(txtValorPlano.getText()));

        // criar objeto alunos
        AlunosModel f = new AlunosModel();
        f = (AlunosModel) cbalunoplano.getSelectedItem();
        obj.setAlunos(f);

        PlanoDao dao = new PlanoDao();
        dao.cadastrar(obj);
        new Utilitarios().LimpaTela(PanelCadastrarPlano);


    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        // botao editar 
        PlanoModel obj = new PlanoModel();
        obj.setDescricao(txtdescricaoplano.getText());
        obj.setValor(Double.parseDouble(txtValorPlano.getText()));
        obj.setId(Integer.parseInt(txtCodigoPlano.getText()));

        AlunosModel f = new AlunosModel();
        f = (AlunosModel) cbalunoplano.getSelectedItem();
        obj.setAlunos(f);

       PlanoDao dao = new PlanoDao();
       //;dao.(obj)
       

    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // carrega a lista
        listar();

    }//GEN-LAST:event_formWindowActivated

    private void tabelaPlanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPlanoMouseClicked
        // pega dados da tabela no click do mouse
        jTabbedPane1.setSelectedIndex(0);// muda de aba volta ao clicar no registro
        txtCodigoPlano.setText(tabelaPlano.getValueAt(tabelaPlano.getSelectedRow(), 0).toString());
        txtdescricaoplano.setText(tabelaPlano.getValueAt(tabelaPlano.getSelectedRow(), 1).toString());
        txtValorPlano.setText(tabelaPlano.getValueAt(tabelaPlano.getSelectedRow(), 2).toString());
       // cbalunoplano.setSelectedItem(tabelaPlano.getValueAt(tabelaPlano.getSelectedRow(), 3).toString());
       
       Alunos f = new Alunos();
       alunosDao dao = new alunosDao();
     // f=dao.alterarAluno(tabelaPlano.getValueAt(tabelaPlano.getSelectedRow(), 3).toString());
       cbalunoplano.removeAllItems();
       cbalunoplano.setSelectedItem(f);
       


    }//GEN-LAST:event_tabelaPlanoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Botao Excluir plano

        PlanoModel obj = new PlanoModel();

        obj.setId(Integer.parseInt(txtCodigoPlano.getText()));
        PlanoDao dao = new PlanoDao();
        dao.excluirPlano(obj);
        new Utilitarios().LimpaTela(PanelCadastrarPlano);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void ButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisaActionPerformed
        // pesquisa por nome
        String nome = "%" + txtpesquisa.getText() + "%";//sintaxe do sql % caracter qualquer coisa antes e depois
        PlanoDao dao = new PlanoDao();
        List<PlanoModel> lista = dao.buscaPlanoPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaPlano.getModel();
        dados.setNumRows(0);
        for (PlanoModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getDescricao(),
                c.getValor(),
                c.getAlunos().getNome()

            });
        }


    }//GEN-LAST:event_ButtonPesquisaActionPerformed

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
       

    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // botao buscar por descricao
        String nome = txtdescricaoplano.getText();
        PlanoModel obj = new PlanoModel();
        PlanoDao dao = new PlanoDao();
        

        obj = (PlanoModel) dao.buscaPlanoPorNome(nome);
        cbalunoplano.removeAllItems();

        if (obj.getDescricao() != null) {

            txtCodigoPlano.setText(String.valueOf(obj.getId()));
            txtdescricaoplano.setText(obj.getDescricao());
            txtValorPlano.setText(String.valueOf(obj.getValor()));

            AlunosModel f = new AlunosModel();
            alunosDao fdao = new alunosDao();

            f = fdao.consultarPorNome(obj.getAlunos().getNome());

            cbalunoplano.getModel().setSelectedItem(f);

        } else {
            JOptionPane.showMessageDialog(null, "Plano não encontrado");
        }

    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvar1ActionPerformed
        // Botao novo

        new Utilitarios().LimpaTela(PanelCadastrarPlano);

    }//GEN-LAST:event_ButtonSalvar1ActionPerformed

    private void ButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonSalvarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSalvarKeyPressed

    private void cbalunoplanoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbalunoplanoAncestorAdded
        // combo box palno
        // instancia classe alunosDao
        alunosDao dao = new alunosDao();
        List<AlunosModel> lista = dao.listarAlunos();
        cbalunoplano.removeAll();// para não coloca  outro registro limpa antes
        for (AlunosModel f : lista) {
            cbalunoplano.addItem(f);

        }


    }//GEN-LAST:event_cbalunoplanoAncestorAdded

    private void cbalunoplanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbalunoplanoMouseClicked
        // busca plano produto
        alunosDao dao = new alunosDao();
        List<AlunosModel> listadeAlunos = dao.listarAlunos();
        cbalunoplano.removeAllItems();

        for (AlunosModel f : listadeAlunos) {
            cbalunoplano.addItem(f);

        }


    }//GEN-LAST:event_cbalunoplanoMouseClicked

    private void ButtonPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPesquisaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPesquisaMouseClicked

    private void cbalunoplanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbalunoplanoActionPerformed
        // seleciona nome combo
        //String nomecombo = cbalunoplano.getSelectedItem().toString();
       // txtdescricaoplano.setText(nomecombo);
      //  AlunosModel obj = new AlunosModel();
        //obj = cbalunoplano.getSelectedItem().toString();
       
       
    }//GEN-LAST:event_cbalunoplanoActionPerformed

    private void PanelCadastrarPlanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCadastrarPlanoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCadastrarPlanoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonPesquisa;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonSalvar1;
    private javax.swing.JLabel LabelCodigoPlano;
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JLabel LabelUf;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JPanel PanelCadastrarPlano;
    private javax.swing.JPanel PanelConsultaAluno;
    private javax.swing.JComboBox cbalunoplano;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaPlano;
    private javax.swing.JTextField txtCodigoPlano;
    private javax.swing.JTextField txtValorPlano;
    private javax.swing.JTextField txtdescricaoplano;
    private javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables
}
