/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProfessorDao;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import model.ProfessoresModel;
import model.Utilitarios;
//import dao.alunosDao;
//import model.Alunos;

/**
 *
 * @author mmgti
 */
public class Professor extends javax.swing.JFrame {

    /**
     * Creates new form Alunos
     */
    //Connection con = null ;
    //PreparedStatement pst = null ;
    //ResultSet rs = null;
    public void listar() {

    }

    public Professor() {
        initComponents();
        // con = conexao.conector();
        //System.out.println(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCadastroProfessor = new javax.swing.JPanel();
        LabelNome = new javax.swing.JLabel();
        txtnomeprof = new javax.swing.JTextField();
        txtcepprof = new javax.swing.JFormattedTextField();
        LabelTelefone = new javax.swing.JLabel();
        txttelefoneprof = new javax.swing.JFormattedTextField();
        LabeCepl = new javax.swing.JLabel();
        LabelEndereco = new javax.swing.JLabel();
        txtnumeroprof = new javax.swing.JTextField();
        LabelNumero = new javax.swing.JLabel();
        txtenderecoprof = new javax.swing.JTextField();
        LabelBairro = new javax.swing.JLabel();
        txtcpf = new javax.swing.JFormattedTextField();
        LabelCpf = new javax.swing.JLabel();
        txtbairroprof = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        LabelMensalidade = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        LabelMensalidade1 = new javax.swing.JLabel();
        txthoras = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        LabelMensalidade2 = new javax.swing.JLabel();
        PanelConsultaAluno = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ButtonPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProfessor = new javax.swing.JTable();
        BotaoSalvar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Professores");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro Professores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Sistema Academia");

        PanelCadastroProfessor.setBackground(new java.awt.Color(255, 255, 255));

        LabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNome.setText("Nome");

        txtnomeprof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            txtcepprof.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcepprof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcepprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcepprofActionPerformed(evt);
            }
        });
        txtcepprof.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcepprofKeyPressed(evt);
            }
        });

        LabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTelefone.setText("Telefone");

        try {
            txttelefoneprof.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefoneprof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabeCepl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabeCepl.setText("CEP");

        LabelEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelEndereco.setText("Endereço");

        txtnumeroprof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNumero.setText("N:");

        txtenderecoprof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelBairro.setText("Bairro");

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        txtcpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcpfKeyPressed(evt);
            }
        });

        LabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCpf.setText("CPF");

        txtbairroprof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonBuscar.setText("Busca");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        LabelMensalidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelMensalidade.setText("Salario");

        txtvalor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelMensalidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelMensalidade1.setText("Horas");

        txthoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txthoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorasActionPerformed(evt);
            }
        });

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelMensalidade2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelMensalidade2.setText("Codigo");

        javax.swing.GroupLayout PanelCadastroProfessorLayout = new javax.swing.GroupLayout(PanelCadastroProfessor);
        PanelCadastroProfessor.setLayout(PanelCadastroProfessorLayout);
        PanelCadastroProfessorLayout.setHorizontalGroup(
            PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastroProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelEndereco)
                    .addComponent(LabelNome)
                    .addComponent(LabelMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ButtonBuscar)
                        .addComponent(txtenderecoprof, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnomeprof, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCadastroProfessorLayout.createSequentialGroup()
                        .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelMensalidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCadastroProfessorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttelefoneprof, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelMensalidade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthoras, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(LabelCpf)
                        .addGap(18, 18, 18)
                        .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCadastroProfessorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumeroprof, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbairroprof)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabeCepl)
                        .addGap(18, 18, 18)
                        .addComponent(txtcepprof, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        PanelCadastroProfessorLayout.setVerticalGroup(
            PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastroProfessorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomeprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNome)
                    .addComponent(txttelefoneprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTelefone)
                    .addComponent(ButtonBuscar)
                    .addComponent(LabelMensalidade1)
                    .addComponent(txthoras, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCpf)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastroProfessorLayout.createSequentialGroup()
                        .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEndereco)
                            .addComponent(txtenderecoprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNumero)
                            .addComponent(txtnumeroprof, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBairro)
                            .addComponent(txtbairroprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMensalidade)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMensalidade2)))
                    .addGroup(PanelCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcepprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabeCepl)))
                .addGap(95, 95, 95))
        );

        jTabbedPane1.addTab("Cadastro Professores", PanelCadastroProfessor);

        PanelConsultaAluno.setBackground(new java.awt.Color(255, 255, 255));

        txtpesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nome");

        ButtonPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonPesquisa.setText("Pesquisar");
        ButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisaActionPerformed(evt);
            }
        });

        tabelaProfessor.setBackground(new java.awt.Color(204, 255, 255));
        tabelaProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CPF", "Telefone", "Cep", "Endereço", "Numero", "Bairro", "Horas", "Salario"
            }
        ));
        tabelaProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProfessorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProfessor);

        javax.swing.GroupLayout PanelConsultaAlunoLayout = new javax.swing.GroupLayout(PanelConsultaAluno);
        PanelConsultaAluno.setLayout(PanelConsultaAlunoLayout);
        PanelConsultaAlunoLayout.setHorizontalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        PanelConsultaAlunoLayout.setVerticalGroup(
            PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaAlunoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ButtonPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Professores", PanelConsultaAluno);

        BotaoSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        BotaoSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotaoSalvarKeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        ButtonEditar.setText("Editar");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonSalvar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        ButtonSalvar1.setText("Novo");
        ButtonSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(ButtonSalvar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvar)
                    .addComponent(ButtonEditar)
                    .addComponent(jButton4)
                    .addComponent(ButtonSalvar1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("CadastroFuncionarios");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        // botao salvar

        ProfessoresModel obj = new ProfessoresModel();

        obj.setNome(txtnomeprof.getText());
        obj.setCpf(txtcpf.getText());
        obj.setEndereco(txtenderecoprof.getText());
        obj.setNumero(Integer.parseInt(txtnumeroprof.getText()));
        obj.setBairro(txtbairroprof.getText());
        obj.setCep(txtcepprof.getText());
        obj.setTelefone(txttelefoneprof.getText());
        obj.setHoras(Integer.parseInt(txthoras.getText()));
        obj.setValor(Integer.parseInt(txtvalor.getText()));

        ProfessorDao dao = new ProfessorDao();
        dao.cadastrar(obj);
        new Utilitarios().LimpaTela(PanelCadastroProfessor);


    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        // botao editar 

        ProfessoresModel obj = new ProfessoresModel();

        obj.setNome(txtnomeprof.getText());
        obj.setCpf(txtcpf.getText());
        obj.setEndereco(txtenderecoprof.getText());
        obj.setNumero(Integer.parseInt(txtnumeroprof.getText()));
        obj.setBairro(txtbairroprof.getText());
        obj.setCep(txtcepprof.getText());
        obj.setTelefone(txttelefoneprof.getText());
        obj.setHoras(Integer.parseInt(txthoras.getText()));
        obj.setValor(Double.parseDouble(txtvalor.getText()));

        ProfessorDao dao = new ProfessorDao();
        dao.alterarProfessor(obj);

        new Utilitarios().LimpaTela(PanelCadastroProfessor);


    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // carrega a lista
        listar();

    }//GEN-LAST:event_formWindowActivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Botao Excluir

        ProfessoresModel obj = new ProfessoresModel();

        obj.setId(Integer.parseInt(txtcodigo.getText()));
        ProfessorDao dao = new ProfessorDao();
        dao.excluirProfessor(obj);
        new Utilitarios().LimpaTela(PanelCadastroProfessor);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void ButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisaActionPerformed
        // pesquisa por nome
        String nome = "%" + txtpesquisa.getText() + "%";//sintaxe do sql % caracter qualquer coisa antes e depois
        ProfessorDao dao = new ProfessorDao();
        List<ProfessoresModel> lista = dao.buscaProfessorPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaProfessor.getModel();
        dados.setNumRows(0);
        for (ProfessoresModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf(),
                c.getTelefone(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getBairro(),
                c.getHoras(),
                c.getValor()});
        }


    }//GEN-LAST:event_ButtonPesquisaActionPerformed

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
        // escreve no campo de pesquisa 
        String nome = "%" + txtpesquisa.getText() + "%";//sintaxe do sql % caracter qualquer coisa antes e depois
        ProfessorDao dao = new ProfessorDao();
        List<ProfessoresModel> lista = dao.buscaProfessorPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaProfessor.getModel();
        dados.setNumRows(0);
        for (ProfessoresModel c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf(),
                c.getEndereco(),
                c.getNumero(),
                c.getBairro(),
                c.getCep(),
                c.getTelefone(),
                c.getHoras(),
                c.getValor(),});
        }

    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void ButtonSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvar1ActionPerformed
        // Botao novo

        new Utilitarios().LimpaTela(PanelCadastroProfessor);

    }//GEN-LAST:event_ButtonSalvar1ActionPerformed

    private void BotaoSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoSalvarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoSalvarKeyPressed

    private void txthorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        // botao buscar por nome
        String nome = txtnomeprof.getText();
        ProfessoresModel obj = new ProfessoresModel();
        ProfessorDao dao = new ProfessorDao();

        obj = dao.consultarProfessorPorNome(nome);

        if (obj.getNome() != null) {

            txtnomeprof.setText(obj.getNome());
            txtcpf.setText(obj.getCpf());
            txttelefoneprof.setText(obj.getTelefone());
            txtcepprof.setText(obj.getCep());
            txtenderecoprof.setText(obj.getEndereco());
            txtnumeroprof.setText(String.valueOf(obj.getNumero()));
            txthoras.setText(String.valueOf(obj.getHoras()));
            txtbairroprof.setText(String.valueOf(obj.getBairro()));
            txtvalor.setText(String.valueOf(obj.getValor()));
            txtcodigo.setText(String.valueOf(obj.getId()));
            // obj.setId(Integer.parseInt(txtcodigo.getText()));

        } else {
            JOptionPane.showMessageDialog(null, "Professor não encontrado");
        }

    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void txtcpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfKeyPressed

    private void txtcepprofKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcepprofKeyPressed
        //Programacao do keypress
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ProfessoresModel obj = new ProfessoresModel();
            ProfessorDao dao = new ProfessorDao();
            obj = dao.ProfessorCep(txtcepprof.getText());

            txtenderecoprof.setText(obj.getEndereco());
            txtbairroprof.setText(obj.getBairro());
            //  txtcidade.setText(obj.getCidade());
            // cbuf.setSelectedItem(obj.getUf());
            // System.out.println(obj.getUf());

        }
    }//GEN-LAST:event_txtcepprofKeyPressed

    private void txtcepprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcepprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcepprofActionPerformed

    private void tabelaProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProfessorMouseClicked
        // pega dados da tabela no click do mouse
        jTabbedPane1.setSelectedIndex(0);// muda de aba volta ao clicar no registro
        txtcodigo.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 0).toString());
        txtnomeprof.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 1).toString());
        txtcpf.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 2).toString());
        txtenderecoprof.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 5).toString());
        txtnumeroprof.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 6).toString());
        txtbairroprof.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 7).toString());
        txtcepprof.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 4).toString());
        txttelefoneprof.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 3).toString());
        txthoras.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 8).toString());
        txtvalor.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 9).toString());
         // txtcodigo.setText(tabelaProfessor.getValueAt(tabelaProfessor.getSelectedRow(), 10).toString());


    }//GEN-LAST:event_tabelaProfessorMouseClicked

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonPesquisa;
    private javax.swing.JButton ButtonSalvar1;
    private javax.swing.JLabel LabeCepl;
    private javax.swing.JLabel LabelBairro;
    private javax.swing.JLabel LabelCpf;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelMensalidade;
    private javax.swing.JLabel LabelMensalidade1;
    private javax.swing.JLabel LabelMensalidade2;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelTelefone;
    private javax.swing.JPanel PanelCadastroProfessor;
    private javax.swing.JPanel PanelConsultaAluno;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaProfessor;
    private javax.swing.JTextField txtbairroprof;
    private javax.swing.JFormattedTextField txtcepprof;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JTextField txtenderecoprof;
    private javax.swing.JTextField txthoras;
    private javax.swing.JTextField txtnomeprof;
    private javax.swing.JTextField txtnumeroprof;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JFormattedTextField txttelefoneprof;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
